## Data transformation 

In the transformation stage, I  Started importing the neccesary  Libraries. Then I loaded my Data Set, I checked my raw data and the and I rename the columns to identfy the right features. So I started look for duplicates observations and missing values to ensure the quality of data. One duplicate row was identified and removed, while no missing values were found in the dataset. Additionally, the variables NdsCH and NdssC were identified as categorical variables because they contained a limited number of unique integer values. To make these variables suitable for linear regression, they were converted into binary indicator variables using one-hot encoding with pd.get_dummies(). The parameter drop_first=True was applied to avoid multicollinearity by removing the first category of each variable. Finally, the cleaned dataset was saved as a new CSV file so it can be used directly in the modeling stage without repeating the transformation steps.

In [3]:
#lest import the necessary libraries to explore the data frame and visualize the data.
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
#Read data with Pandas 
df = pd.read_csv('/Users/ingxrodriguez/Phase1-Linear-Regression-Model/Phase1-Linear-Regression-Model/Data/qsar_fish_toxicity.csv',header=None,sep=';')

In [7]:
#Let's check the first 5 rows of the data frame to see what the data looks like.
print(df.head())

       0      1      2  3  4      5      6
0  3.260  0.829  1.676  0  1  1.453  3.770
1  2.189  0.580  0.863  0  0  1.348  3.115
2  2.125  0.638  0.831  0  0  1.348  3.531
3  3.027  0.331  1.472  1  0  1.807  3.510
4  2.094  0.827  0.860  0  0  1.886  5.390

In [8]:
#oh oh I need to add names for each column, otherwise it will be hard to work with the data

df.columns = ["CIC0","SM1_Dz(Z)","GATS1i", "NdsCH","NdssC", "MLOGP","LC50"]

In [9]:
#let's check the data again to see if the names were added correctly
df.head(7)

    CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP   LC50
0  3.260      0.829   1.676      0      1  1.453  3.770
1  2.189      0.580   0.863      0      0  1.348  3.115
2  2.125      0.638   0.831      0      0  1.348  3.531
3  3.027      0.331   1.472      1      0  1.807  3.510
4  2.094      0.827   0.860      0      0  1.886  5.390
5  3.222      0.331   2.177      0      0  0.706  1.819
6  3.179      0.000   1.063      0      0  2.942  3.947

# Duplicate Observations 
check for duplicate observations was performed using the duplicated() function. The results show that there are no duplicate rows in the dataset, indicating that each observation is unique and no duplicate removal is required.

In [10]:
#let's check for duplicates in the data frame. We can use the duplicated() method to check for duplicates in the data frame.
print(df)
print()
print(df.duplicated())

      CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP   LC50
0    3.260      0.829   1.676      0      1  1.453  3.770
1    2.189      0.580   0.863      0      0  1.348  3.115
2    2.125      0.638   0.831      0      0  1.348  3.531
3    3.027      0.331   1.472      1      0  1.807  3.510
4    2.094      0.827   0.860      0      0  1.886  5.390
..     ...        ...     ...    ...    ...    ...    ...
903  2.801      0.728   2.226      0      2  0.736  3.109
904  3.652      0.872   0.867      2      3  3.983  4.040
905  3.763      0.916   0.878      0      6  2.918  4.818
906  2.831      1.393   1.077      0      1  0.906  5.317
907  4.057      1.032   1.183      1      3  4.754  8.201

[908 rows x 7 columns]

0      False
1      False
2      False
3      False
4      False
       ...
903    False
904    False
905    False
906    False
907    False
Length: 908, dtype: bool

In [11]:
#let's verify again because in my exploratory analysis I found that there are 1 duplicate in the data frame, but I want to be sure.
df.duplicated().sum()

np.int64(1)

In [12]:
#ok lest delete the duplicates "np.int64(1)"
df = df.drop_duplicates()

In [13]:
#Now let's check again for duplicates to see if they were deleted correctly.
df.duplicated().sum()

np.int64(0)

In [14]:
print(df)
print()
print(df.duplicated())

      CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP   LC50
0    3.260      0.829   1.676      0      1  1.453  3.770
1    2.189      0.580   0.863      0      0  1.348  3.115
2    2.125      0.638   0.831      0      0  1.348  3.531
3    3.027      0.331   1.472      1      0  1.807  3.510
4    2.094      0.827   0.860      0      0  1.886  5.390
..     ...        ...     ...    ...    ...    ...    ...
903  2.801      0.728   2.226      0      2  0.736  3.109
904  3.652      0.872   0.867      2      3  3.983  4.040
905  3.763      0.916   0.878      0      6  2.918  4.818
906  2.831      1.393   1.077      0      1  0.906  5.317
907  4.057      1.032   1.183      1      3  4.754  8.201

[907 rows x 7 columns]

0      False
1      False
2      False
3      False
4      False
       ...
903    False
904    False
905    False
906    False
907    False
Length: 907, dtype: bool

# Summary Duplicate Observations 
it looks like there are one duplicate row in the data frame. it is already clean. 
additionally, I identify 2  categorical variables: NdsCH and NdssC

# Fixing Categorical Variables 

Lest use dummies to convert the categorical variables into numerical variables. I  use the get_dummies() method to convert the categorical variables into numerical variables(one-hot encoding) is a way to convert categorical variables (labels or groups) into numeric columns 1 and 0 or Bolean values True and False. This is useful for machine learning algorithms that can only work with numerical data. The get_dummies() method takes the data frame and the columns that we want to convert into dummy variables. The drop_first=True parameter is used to drop the first column of the dummy variables to avoid multicollinearity.

In [15]:
#A function that converts categorical values into new binary columns—one for each different category

Clean_df = pd.get_dummies(df, columns=['NdsCH', 'NdssC'], drop_first=True)

Clean_df.head()

,CIC0,SM1_Dz(Z),GATS1i,MLOGP,LC50,NdsCH_1,NdsCH_2,NdsCH_3,NdsCH_4,NdssC_1,NdssC_2,NdssC_3,NdssC_4,NdssC_5,NdssC_6
0,3.260,0.829,1.676,1.453,3.770,False,False,False,False,True,False,False,False,False,False
1,2.189,0.580,0.863,1.348,3.115,False,False,False,False,False,False,False,False,False,False
2,2.125,0.638,0.831,1.348,3.531,False,False,False,False,False,False,False,False,False,False
3,3.027,0.331,1.472,1.807,3.510,True,False,False,False,False,False,False,False,False,False
4,2.094,0.827,0.860,1.886,5.390,False,False,False,False,False,False,False,False,False,False

# Let's save my beautiful data set

Finally, we've cleaned our dataset and it's ready for modeling. Let's check once there are no categorical variables and then save it as Clean_qsar_fish_Toxicity.cvs in our carpet name DATA

In [16]:
#lest check the data frame again to see if the new columns were added correctly.
Clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 907 entries, 0 to 907
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CIC0       907 non-null    float64
 1   SM1_Dz(Z)  907 non-null    float64
 2   GATS1i     907 non-null    float64
 3   MLOGP      907 non-null    float64
 4   LC50       907 non-null    float64
 5   NdsCH_1    907 non-null    bool
 6   NdsCH_2    907 non-null    bool
 7   NdsCH_3    907 non-null    bool
 8   NdsCH_4    907 non-null    bool
 9   NdssC_1    907 non-null    bool
 10  NdssC_2    907 non-null    bool
 11  NdssC_3    907 non-null    bool
 12  NdssC_4    907 non-null    bool
 13  NdssC_5    907 non-null    bool
 14  NdssC_6    907 non-null    bool
dtypes: bool(10), float64(5)
memory usage: 51.4 KB

In [17]:
#ok, lest's save our clean data frame as a new csv file so we can use it later for our model.
Clean_df.to_csv('/Users/ingxrodriguez/Phase1-Linear-Regression-Model/Phase1-Linear-Regression-Model/Data/Clean_qsar_fish_toxicity.csv', index=False)